server:
  port: 7005
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CampusRecruitment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 10
    maxActive: 100

  application:
    name: cr-user-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    hostname: localhost

